# Generated by Django 5.1.1 on 2024-09-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(null=True),
        ),
    ]
